PACKAGE_NAME="minimem"
PACKAGE_VERSION="0.8.0"
BUILT_MODULE_NAME="minimem"
DEST_MODULE_LOCATION="/extra"

AUTOINSTALL="yes"

PATCHES=(patches/minimem-6.18-fault-handler-registration.patch
         patches/minimem-6.18-handle-minimem-marker.patch)

POST_INSTALL="install.sh"
PRE_REMOVE="uninstall.sh"